perf: bump to 7.0
This removes support for libunwind because otherwise we get a linker error:

  unwind-libunwind.c:86: multiple definition of `unwind__get_entries'

See this commit for more information:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/tools/perf?id=2e9191573a69ff962b018d85a2c58269a1637b27